# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-06 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='online',
            field=models.BooleanField(default=False),
        ),
    ]
